-- Run this once in Supabase Dashboard -> SQL Editor.
-- It creates a private queue used by the shop printer agent.

create table if not exists public.print_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null check (job_type in ('order', 'rental')),
  record_id bigint not null,
  status text not null default 'pending'
    check (status in ('pending', 'printing', 'printed', 'failed')),
  attempts integer not null default 0,
  requested_at timestamptz not null default now(),
  claimed_at timestamptz,
  printed_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_type, record_id)
);

create index if not exists print_jobs_queue_index
  on public.print_jobs (status, requested_at);

alter table public.print_jobs enable row level security;

-- No browser policies are created. Only the service-role server code can access it.

create or replace function public.set_print_jobs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_print_jobs_updated_at on public.print_jobs;

create trigger set_print_jobs_updated_at
before update on public.print_jobs
for each row
execute function public.set_print_jobs_updated_at();
